'use strict';
const Classroom=(()=>{
 const cfg=window.YUNGA_AUTH_CONFIG||{},base=(cfg.supabaseUrl||'').replace(/\/$/,'');
 let teacherGeneration=0;
 let session=null,localState=null,student=false,studentMessage='',busy=false,bundle=null,teacherBundle=null,teacherId='',triedId='',loading=false,teacherError='',queue=[],syncing=false,syncTimer;
 const mime=new Set(['image/jpeg','image/png','image/webp','application/pdf','audio/mpeg','audio/mp4','audio/ogg','video/mp4','video/webm']);
 async function fetchAPI(path,body,access,method='POST',file=null){
  const headers={apikey:cfg.publishableKey};if(access)headers.Authorization='Bearer '+access;
  if(!file)headers['Content-Type']='application/json';else headers['Content-Type']=file.type;
  let response;try{response=await fetch(base+path,{method,headers,body:file||JSON.stringify(body),cache:'no-store',signal:AbortSignal.timeout(file?60000:15000)});}catch{throw Error('No se pudo conectar. Conserva esta pestaña y vuelve a intentar.');}
  const data=await response.json().catch(()=>null);
  if(!response.ok){const err=Error(response.status===429?'Demasiados intentos. Espera y vuelve a probar.':path.includes('grant_type=password')?'Correo o contraseña incorrectos, o cuenta no confirmada.':data?.message||data?.msg||'No se pudo completar la operación.');err.code=data?.code;err.status=response.status;throw err;}
  return data;
 }
 async function token(){if(!session)throw Error('Inicia sesión como estudiante.');if(Date.now()/1000>session.expires_at-60){const n=await fetchAPI('/auth/v1/token?grant_type=refresh_token',{refresh_token:session.refresh_token});session={...n,expires_at:Date.now()/1000+n.expires_in};}return session.access_token;}
 async function rpc(name,body={}){return fetchAPI('/rest/v1/rpc/'+name,body,await token());}
 function studentLogin(){
  if(Teacher.isCloud())return title('Acceso estudiante','Cada estudiante tiene su propio espacio.')+`<div class="notice">Cierra la sesión docente antes de entrar como estudiante.</div><a class="btn" href="#docente">Ir al panel docente</a>`;
  return title('Entrar a mis tareas','Trabaja desde casa y comparte lo que aprendiste.')+`<div class="card auth-card"><span class="auth-mark">YS</span><h2>Tu espacio de estudiante</h2><p>Usa la cuenta que tu docente te entregó. También puede ser una cuenta de tu representante.</p>${Teacher.ready?`<form id="student-login-form"><div class="field"><label for="student-email">Correo de tu cuenta</label><input id="student-email" type="email" autocomplete="username" required maxlength="254"></div><div class="field"><label for="student-password">Contraseña</label><input id="student-password" type="password" autocomplete="current-password" required maxlength="1024"></div><button class="btn" ${busy?'disabled':''}>${busy?'Entrando…':'Entrar a mis tareas'}</button></form>`:'<div class="notice">El acceso aún no está configurado.</div>'}${studentMessage?`<p role="alert" class="auth-message">${E(studentMessage)}</p>`:''}<p><a href="#acceso">Volver a los accesos</a></p><a href="#practica">Practicar sin cuenta →</a></div>`;
 }
 function absorb(data,quiz=null){
  if(!data?.profile)throw Error('Tu docente debe asignar tu cuenta a un perfil.');
  const profile=JSON.parse(JSON.stringify(data.profile));profile.quiz=quiz;
  const seen=new Set((profile.logs||[]).map(x=>x.id));
  for(const e of data.events||[])if(!seen.has(e.id)&&byId(e.lesson)){profile.logs.push(e);seen.add(e.id);}
  profile.logs=profile.logs.slice(-1000);
  const clean=sanitize({version:1,active:profile.id,students:[profile]});state=clean;bundle=data;
 }
 async function login(form){
  if(busy||student||Teacher.isCloud()||!Teacher.ready||!form.reportValidity())return;
  const email=$('#student-email').value.trim().toLowerCase(),password=$('#student-password').value;
  busy=true;studentMessage='';render();
  try{
   const n=await fetchAPI('/auth/v1/token?grant_type=password',{email,password});session={...n,expires_at:Date.now()/1000+n.expires_in};
   const home=await rpc('yunga_class_home');localState=state;
   absorb(home);student=true;game=null;lessonTab='aprender';location.hash='estudiante';closeModal();
  }catch(error){if(session)fetchAPI('/auth/v1/logout',{},session.access_token).catch(()=>{});session=null;studentMessage=error.code==='PGRST202'?'Tu docente aún debe activar las tareas en línea.':error.message;}
  finally{busy=false;render();stamp();}
 }
 function stamp(){if(student&&$('#access-label'))$('#access-label').textContent='Estudiante · '+(queue.length||syncing?'Resultados pendientes':studentMessage?'Revisar conexión':'Conectado');}
 function assignment(t){
  const sub=bundle?.submissions?.find(s=>s.task_id===t.id),stateName=sub?{enviado:'Entregada · por revisar',correccion:'Corrección solicitada',revisado:'Revisada'}[sub.state]:'Pendiente';
  return `<article class="card assignment"><div class="section-head"><h3>${E(t.title)}</h3><span class="badge ${sub?.state==='correccion'?'warn':''}">${stateName}</span></div><p class="muted">${E(t.format)} · ${dateLabel(t.date)}</p>${t.lesson?`<a href="#tema/${E(t.lesson)}">Practicar el tema →</a>`:''}<p class="preserve">${E(t.notes)}</p>${sub?.feedback?`<div class="callout"><strong>Tu docente te comenta:</strong><p class="preserve">${E(sub.feedback)}</p></div>`:''}${sub?`<p><small>Última entrega: ${dateLabel(sub.submitted_at)}</small></p>${fileButtons(sub)}`:''}${sub?.state!=='revisado'?button(sub?'Corregir o reenviar':'Entregar mi trabajo','class-submit',`data-task="${E(t.id)}"`):'<p class="muted">Trabajo revisado. Si necesitas reenviar, pide a tu docente que lo habilite.</p>'}</article>`;
 }
 function studentHome(){if(!student)return studentLogin();return title('Mis tareas',`Hola, ${E(current().name)}. Estas son las actividades que tu docente te asignó.`)+`<div class="notice teacher-session"><div><strong>${E(session.user.email)}</strong><br><small>Las entregas y resultados completados se comparten con tu docente. Un intento sin terminar permanece en esta pestaña.</small></div><div class="actions">${button('Actualizar tareas','class-refresh','','secondary small')}${button('Cerrar sesión','class-logout','','secondary small')}</div></div>${studentMessage?`<div class="auth-message" role="alert">${E(studentMessage)} ${button('Reintentar resultados','class-sync','','secondary small')}</div>`:''}<div class="assignment-list">${current().tasks.length?current().tasks.map(assignment).join(''):'<div class="empty">Tu docente todavía no ha asignado tareas.</div>'}</div><p class="muted">También puedes explorar temas y practicar juegos. Tu docente valora las exposiciones y el dominio del tema.</p>`;}
 function fileButtons(sub){return `<div class="actions attachment-list">${(sub.files||[]).map((f,i)=>button('↓ '+E(f.name),'class-download',`data-sub="${E(sub.id)}" data-index="${i}"`,'secondary small')).join('')}</div>`;}
 function ensureTeacher(){if(Teacher.isAllowed()&&triedId!==current().id&&!loading){triedId=current().id;setTimeout(()=>refreshTeacher(),0);}}
 function teacherPanel(){
  if(!Teacher.isAllowed())return '';ensureTeacher();
  const b=teacherId===current().id?teacherBundle:null;
  return `<section class="card classroom-panel"><div class="section-head"><h2>Trabajo en casa</h2>${button('Actualizar entregas','class-teacher-refresh','','secondary small')}</div>${loading?'<p role="status">Consultando entregas…</p>':''}${teacherError?`<div class="notice">${E(teacherError)} <a href="https://github.com/yunga18/Control-de-tareas-y-refuerzo-acad-mico-/blob/main/TRABAJO-EN-CASA.md" target="_blank" rel="noopener">Ver pasos de activación</a></div>`:''}${b?`<p>${b.email?'Cuenta del estudiante: <strong>'+E(b.email)+'</strong>':'Este perfil todavía no tiene una cuenta asociada.'}</p><div class="actions">${button(b.email?'Cambiar cuenta estudiantil':'Habilitar cuenta estudiantil','class-enroll','','secondary')}${b.email?button('Valorar dominio de un tema','class-mastery','','secondary')+button('Exportar revisión','class-export','','secondary'):''}</div><p class="muted"><small>Asigna actividades desde «Clases y tareas». Las pruebas y juegos realizados con la cuenta estudiantil se incorporan al progreso al actualizar este panel.</small></p><div class="submission-list">${b.submissions.length?b.submissions.map(s=>{const t=current().tasks.find(t=>t.id===s.task_id);return `<article class="submission"><h3>${E(t?.title||'Actividad retirada de la planificación')}</h3><p><span class="badge ${s.state==='enviado'?'warn':''}">${{enviado:'Por revisar',correccion:'Corrección solicitada',revisado:'Revisada'}[s.state]}</span> · ${dateLabel(s.submitted_at)}</p><p class="preserve">${E(s.answer)}</p>${safeLink(s.link)}${fileButtons(s)}${s.feedback?`<div class="callout"><strong>Devolución:</strong><p class="preserve">${E(s.feedback)}</p></div>`:''}<div class="actions">${button('Revisar entrega','class-review',`data-sub="${E(s.id)}"`)}${s.files.length?button('Retirar adjuntos','class-clear-files',`data-sub="${E(s.id)}"`,'danger small'):''}</div></article>`;}).join(''):'<div class="empty">Todavía no hay entregas para este estudiante.</div>'}</div>`:''}</section>`;
 }
 function safeLink(url){try{const u=new URL(url);if(!['http:','https:'].includes(u.protocol))return '';return `<p><a href="${E(u.href)}" target="_blank" rel="noopener noreferrer">Abrir enlace entregado ↗</a></p>`;}catch{return '';}}
 async function refreshTeacher(force=false){
  if(!Teacher.isAllowed()||loading||busy&&!force)return;const id=current().id,generation=++teacherGeneration;loading=true;teacherError='';render();
  try{const data=await Teacher.rpc('yunga_class_teacher',{p_student:id});if(generation!==teacherGeneration||!Teacher.isAllowed()||current().id!==id)return;teacherBundle=data;teacherId=id;
   const seen=new Set(current().logs.map(x=>x.id));let changed=false;for(const e of data.events||[])if(!seen.has(e.id)&&byId(e.lesson)){current().logs.push(e);seen.add(e.id);changed=true;}if(changed){current().logs=current().logs.slice(-1000);save();}
  }catch(error){if(generation!==teacherGeneration)return;teacherError=error.code==='PGRST202'?'Las tareas en línea están pendientes de activación. Ejecuta la ampliación SQL una vez en Supabase.':error.message;}
  finally{if(generation===teacherGeneration){loading=false;render();}}
 }
 async function refreshStudent(){
  if(!student||busy)return;busy=true;try{await sync();if(queue.length)throw Error('Hay resultados pendientes. Reintenta antes de actualizar.');const quiz=current().quiz;absorb(await rpc('yunga_class_home'),quiz);studentMessage='';}catch(error){studentMessage=error.message;toast(studentMessage);}finally{busy=false;render();stamp();}
 }
 function mastery(id){const b=student?bundle:teacherId===current().id?teacherBundle:null;return b?.mastery?.find(m=>m.lesson===id);}
 function record(event){if(!student||!['diag','knowledge','match','puzzle'].includes(event.type))return;queue.push({...event});clearTimeout(syncTimer);syncTimer=setTimeout(sync,700);stamp();}
 async function sync(){if(!student||syncing||!queue.length)return;syncing=true;stamp();try{while(queue.length){const batch=queue.slice(0,100);await rpc('yunga_class_sync',{p_events:batch});queue.splice(0,batch.length);}studentMessage='';}catch(error){studentMessage='Resultados pendientes: '+error.message;toast(studentMessage);}finally{syncing=false;stamp();}}
 async function logout(force=false){if(busy||syncing){toast('Espera a que termine la operación.');return;}if(!force){await sync();if(queue.length){openModal(`<h2>Hay resultados sin enviar</h2><p>Reintenta o exporta una copia antes de salir.</p><div class="actions">${button('Exportar copia','export')}${button('Seguir trabajando','close-modal','','secondary')}${button('Salir sin enviar','class-discard','','danger')}</div>`);return;}}const old=session;session=null;student=false;bundle=null;queue=[];studentMessage='';clearTimeout(syncTimer);if(localState)state=localState;localState=null;game=null;closeModal();location.hash='acceso';render();if(old)fetchAPI('/auth/v1/logout',{},old.access_token).catch(()=>{});}
 function submitModal(task){const t=current().tasks.find(t=>t.id===task);if(!t||!student)return;const old=bundle.submissions.find(s=>s.task_id===task);openModal(`<h2>Entregar: ${E(t.title)}</h2><form id="class-submit-form" data-task="${E(task)}"><div class="field"><label for="class-answer">Respuesta o explicación</label><textarea id="class-answer" maxlength="10000" placeholder="Explica qué hiciste y qué aprendiste">${E(old?.answer||'')}</textarea></div><div class="field"><label for="class-link">Enlace opcional a tu trabajo</label><input id="class-link" type="url" maxlength="2000" value="${E(old?.link||'')}" placeholder="https://…"></div><div class="field"><label for="class-files">Adjuntos nuevos (hasta 3, máximo 5 MB cada uno)</label><input id="class-files" type="file" multiple accept="image/jpeg,image/png,image/webp,application/pdf,audio/mpeg,audio/mp4,audio/ogg,video/mp4,video/webm"></div><p class="muted"><small>Se aceptan fotos, PDF, audio y videos pequeños. Si eliges archivos nuevos, reemplazan los adjuntos de la entrega anterior. Si no eliges ninguno, se conservan. Las grabaciones largas pueden enviarse como enlace.</small></p><button class="btn">${busy?'Enviando…':'Enviar a mi docente'}</button><p id="class-upload-status" role="status"></p></form>`);}
 async function submit(form){
  if(!student||busy||!form.reportValidity())return;
  const answer=$('#class-answer').value.trim(),link=$('#class-link').value.trim(),files=Array.from($('#class-files').files),task=form.dataset.task,old=bundle.submissions.find(s=>s.task_id===task);
  if(files.length>3||files.some(f=>!mime.has(f.type)||f.size>5*1024*1024||!f.size)){toast('Elige hasta 3 archivos compatibles de máximo 5 MB cada uno.');return;}if(!answer&&!link&&!files.length&&!old?.files?.length){toast('Añade una respuesta, un enlace o un archivo.');return;}
  busy=true;form.querySelector('button').disabled=true;const uploaded=[];let committed=false;
  try{
   for(const f of files){const ext={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','application/pdf':'pdf','audio/mpeg':'mp3','audio/mp4':'m4a','audio/ogg':'ogg','video/mp4':'mp4','video/webm':'webm'}[f.type];const filePath=current().id+'/'+task+'/'+uid()+'.'+ext;if($('#class-upload-status'))$('#class-upload-status').textContent='Subiendo '+f.name+'…';await fetchAPI('/storage/v1/object/yunga-entregas/'+filePath,null,await token(),'POST',f);uploaded.push({path:filePath,name:f.name.slice(0,180),size:f.size});}
   await rpc('yunga_class_submit',{p_task:task,p_answer:answer,p_link:link,p_files:files.length?uploaded:old?.files||[]});committed=true;
   if(files.length&&old?.files?.length)try{await fetchAPI('/storage/v1/object/yunga-entregas',{prefixes:old.files.map(f=>f.path)},await token(),'DELETE');}catch{/* La entrega ya está guardada; los archivos anteriores se pueden retirar luego. */}
   bundle=await rpc('yunga_class_home');closeModal();toast('Entrega enviada. Tu docente ya puede revisarla.');studentMessage='';
  }catch(error){if(!committed&&uploaded.length)try{await fetchAPI('/storage/v1/object/yunga-entregas',{prefixes:uploaded.map(f=>f.path)},await token(),'DELETE');}catch{}toast((committed?'Tu entrega se guardó, pero no se pudo actualizar la vista. ':'No se envió la entrega. ')+error.message);if($('#class-upload-status'))$('#class-upload-status').textContent=error.message;}
  finally{busy=false;if(form.isConnected)form.querySelector('button').disabled=false;render();}
 }
 function enrollModal(){if(!Teacher.requireTeacher())return;openModal(`<h2>Cuenta de ${E(current().name)}</h2><p>Asocia una cuenta estudiantil o de su representante a este perfil. Cada correo se vincula a un solo estudiante.</p><form id="class-enroll-form"><div class="field"><label for="class-email">Correo de la cuenta estudiantil</label><input id="class-email" type="email" required maxlength="254" value="${E(teacherBundle?.email||'')}"></div><p class="muted"><small>La cuenta debe estar creada y confirmada por la administración. Entrega al estudiante su correo, contraseña y el enlace de acceso.</small></p><button class="btn">Habilitar acceso a este perfil</button></form>`);}
 function reviewModal(id){if(!Teacher.requireTeacher())return;const s=teacherBundle?.submissions.find(s=>s.id===id);if(!s)return;openModal(`<h2>Revisar entrega</h2><form id="class-review-form" data-sub="${E(id)}" data-revision="${s.revision}"><div class="field"><label for="class-review-state">Resultado de revisión</label><select id="class-review-state"><option value="revisado">Revisada</option><option value="correccion" ${s.state==='correccion'?'selected':''}>Solicitar corrección</option></select></div><div class="field"><label for="class-feedback">Devolución al estudiante</label><textarea id="class-feedback" maxlength="5000" required placeholder="Qué logró y cuál es su siguiente paso">${E(s.feedback)}</textarea></div><p class="muted">Revisar una tarea no consolida automáticamente el tema. Usa la rúbrica o la valoración docente del dominio.</p><button class="btn">Guardar y compartir devolución</button></form>`);}
 function masteryModal(){if(!Teacher.requireTeacher()||!teacherBundle?.email)return;openModal(`<h2>Valorar dominio de un tema</h2><form id="class-mastery-form"><div class="field"><label for="class-lesson">Tema</label><select id="class-lesson">${LESSONS.map(l=>`<option value="${l.id}">${E(l.title)}</option>`).join('')}</select></div><div class="field"><label for="class-mastery-state">Decisión docente</label><select id="class-mastery-state"><option value="true">Marcar consolidado</option><option value="false">Reabrir: necesita refuerzo</option><option value="auto">Volver a la regla automática</option></select></div><div class="field"><label for="class-reason">Evidencia y justificación</label><textarea id="class-reason" maxlength="3000" required placeholder="Qué observaste y por qué tomas esta decisión"></textarea></div><button class="btn">Guardar valoración</button></form>`);}
 async function teacherForm(form){if(!Teacher.requireTeacher()||busy||!form.reportValidity())return;busy=true;form.querySelector('button').disabled=true;
  try{if(form.id==='class-enroll-form')save();if(!(await Teacher.flush()))throw Error('Primero resuelve el guardado pendiente del espacio docente.');if(form.id==='class-enroll-form')await Teacher.rpc('yunga_class_enroll',{p_student:current().id,p_email:$('#class-email').value.trim().toLowerCase()});
   if(form.id==='class-review-form')await Teacher.rpc('yunga_class_review',{p_id:form.dataset.sub,p_revision:Number(form.dataset.revision),p_state:$('#class-review-state').value,p_feedback:$('#class-feedback').value.trim()});
   if(form.id==='class-mastery-form'){const v=$('#class-mastery-state').value;await Teacher.rpc('yunga_class_mastery',{p_student:current().id,p_lesson:$('#class-lesson').value,p_state:v==='auto'?null:v==='true',p_reason:$('#class-reason').value.trim()});}
   closeModal();await refreshTeacher(true);toast('Guardado y disponible para el estudiante.');
  }catch(error){toast(error.message);if(form.isConnected)form.querySelector('button').disabled=false;}finally{busy=false;}
 }
 async function download(id,index){const s=(student?bundle:teacherBundle)?.submissions.find(s=>s.id===id),f=s?.files[index];if(!f)return;try{const access=student?await token():await Teacher.token();const signed=await fetchAPI('/storage/v1/object/sign/yunga-entregas/'+f.path,{expiresIn:60},access);const u=new URL(signed.signedURL||signed.signedUrl,base+'/storage/v1/');if(u.origin!==new URL(base).origin)throw Error('Enlace de descarga no válido');if(u.pathname.startsWith('/object/'))u.pathname='/storage/v1'+u.pathname;const response=await fetch(u.href);if(!response.ok)throw Error('Archivo no disponible');const url=URL.createObjectURL(await response.blob()),a=document.createElement('a');a.href=url;a.download=f.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(error){toast(error.message);}}
 function clearFilesModal(id){if(!Teacher.requireTeacher())return;openModal(`<h2>Retirar adjuntos para liberar espacio</h2><p>Descarga los archivos que necesitas conservar antes de retirarlos. La respuesta y la devolución permanecerán.</p><div class="actions">${button('Retirar archivos','class-confirm-clear',`data-sub="${E(id)}"`,'danger')}${button('Cancelar','close-modal','','secondary')}</div>`);}
 async function clearFiles(id){if(!Teacher.requireTeacher()||busy)return;const s=teacherBundle?.submissions.find(s=>s.id===id);if(!s)return;busy=true;try{await fetchAPI('/storage/v1/object/yunga-entregas',{prefixes:s.files.map(f=>f.path)},await Teacher.token(),'DELETE');await Teacher.rpc('yunga_class_clear_files',{p_id:id});closeModal();await refreshTeacher(true);toast('Adjuntos retirados; la devolución se conserva.');}catch(error){toast(error.message);}finally{busy=false;}}
 function cleanupModal(mode){
  if(student||busy||Teacher.isCloud()&&!Teacher.requireTeacher())return;
  const remove=mode==='delete',id=current().id;
  openModal(`<h2>${remove?'Eliminar estudiante':'Borrar datos de prueba'}</h2><p><strong>${E(current().name)}</strong></p><p>${remove?'Se eliminarán este perfil, su asociación estudiantil, tareas, resultados, entregas, archivos y valoraciones.':'Se borrarán sus tareas, resultados, intentos, entregas, archivos y valoraciones. Se conservan el perfil y la cuenta asociada.'} Los demás estudiantes se conservan.</p><p>Esta acción no se puede deshacer. Puedes exportar una copia antes de continuar. La cuenta de acceso en Supabase no se elimina.</p><div class="actions">${button('Exportar copia','export','','secondary')}${button('Cancelar','close-modal','','secondary')}${button(remove?'Eliminar este estudiante':'Borrar los datos de este estudiante','class-cleanup',`data-mode="${mode}" data-student="${E(id)}"`,'danger')}</div><p id="cleanup-status" role="status"></p>`);
 }
 async function cleanup(mode,id){
  if(student||busy||id!==current().id)return;
  if(!Teacher.isCloud()){
   if(mode==='delete'){state.students=state.students.filter(s=>s.id!==id);if(!state.students.length)state.students=[newStudent('Mi estudiante')];state.active=state.students[0].id;}
   else{current().logs=[];current().tasks=[];current().quiz=null;}
   save();game=null;closeModal();render();toast('Datos de este perfil borrados.');return;
  }
  if(!Teacher.requireTeacher())return;busy=true;teacherGeneration++;loading=false;
  const buttons=$('#modal-content').querySelectorAll('button');buttons.forEach(b=>b.disabled=true);
  try{
   if(!(await Teacher.flush()))throw Error('Primero resuelve el guardado pendiente del espacio docente.');
   const preview=await Teacher.rpc('yunga_class_cleanup_preview',{p_student:id,p_revision:Teacher.getRevision()});
   if($('#cleanup-status'))$('#cleanup-status').textContent='Retirando archivos de este estudiante…';
   if(preview.files.length)await fetchAPI('/storage/v1/object/yunga-entregas',{prefixes:preview.files},await Teacher.token(),'DELETE');
   const data=await Teacher.rpc('yunga_class_cleanup',{p_student:id,p_revision:Teacher.getRevision(),p_mode:mode});
   Teacher.adoptWorkspace(data);game=null;closeModal();render();toast(mode==='delete'?'Estudiante eliminado.':'Datos borrados; el perfil y su acceso se conservan.');
  }catch(error){const msg=error.code==='PGRST202'?'Para borrar también los datos en nube, ejecuta de nuevo el archivo classroom.sql actualizado en Supabase.':error.message;if($('#cleanup-status'))$('#cleanup-status').textContent=msg;toast(msg);buttons.forEach(b=>b.disabled=false);}
  finally{busy=false;}
 }
 function exportReview(){if(!Teacher.requireTeacher()||teacherId!==current().id||!teacherBundle)return;const url=URL.createObjectURL(new Blob([JSON.stringify(teacherBundle,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='yunga-revision-'+current().id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Copia de revisión exportada. Descarga los adjuntos por separado.');}
 document.addEventListener('submit',event=>{const f=event.target;if(f.id==='student-login-form'){event.preventDefault();login(f);}if(f.id==='class-submit-form'){event.preventDefault();submit(f);}if(['class-enroll-form','class-review-form','class-mastery-form'].includes(f.id)){event.preventDefault();teacherForm(f);}});
 document.addEventListener('click',event=>{const b=event.target.closest('[data-action]');if(!b||b.disabled)return;switch(b.dataset.action){case'class-cleanup':cleanup(b.dataset.mode,b.dataset.student);break;case'class-refresh':refreshStudent();break;case'class-sync':sync();break;case'class-logout':logout();break;case'class-discard':logout(true);break;case'class-submit':submitModal(b.dataset.task);break;case'class-teacher-refresh':refreshTeacher();break;case'class-enroll':enrollModal();break;case'class-export':exportReview();break;case'class-review':reviewModal(b.dataset.sub);break;case'class-mastery':masteryModal();break;case'class-download':download(b.dataset.sub,Number(b.dataset.index));break;case'class-clear-files':clearFilesModal(b.dataset.sub);break;case'class-confirm-clear':clearFiles(b.dataset.sub);break;}});
 document.querySelector('#modal').addEventListener('cancel',event=>{if(busy)event.preventDefault();});
 window.addEventListener('beforeunload',event=>{if(busy||student&&(queue.length||syncing)){event.preventDefault();event.returnValue='';}});
 window.addEventListener('online',()=>sync());
 return {isStudent:()=>student,isBusy:()=>busy,pendingTasks:()=>current().tasks.filter(t=>bundle?.submissions?.find(s=>s.task_id===t.id)?.state!=='revisado').length,cleanupModal,studentHome,teacherPanel,mastery,record,stamp,resetTeacher:()=>{teacherGeneration++;loading=false;teacherBundle=null;teacherId='';triedId='';teacherError='';}};
})();
